### ISSUE TITLE
Predefined account is not showed in the configuration 

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-playground#119]
The accounts are present when starting the playground locally, but on testing the config account is empty

**Comment by sadiqevani** [comment]
@maptuhec This is not a bug, your state is saved in the local storage, so in case you've been playing with the configuration its going to display what you have saved.

**Comment by sadiqevani** [comment]
A solution to this problem is to add a button that "resets" the configuration.

**Comment by maptuhec** [comment]
@sadiqevani Actually if you delete the cached information, the configuration is empty (null), which is not fine. Also when you click "Save" nothing happens the configuration is not updated in the editor. In my opinion, we should load the application with the default config that we have set for the playground. We are setting it because we believe that thus it will deliver the great development experience without any issues.  Why do you think that with the current version of the playgroudn we should load the configs from the local storage?

New users have the error "Cannot read property 'getContractInstance' of null
~ this.instance.compile is not a function" which I guess is because we are reading it from the local storage.

**Comment by sadiqevani** [comment]
@maptuhec 

1. Actually if you delete the cached information, the configuration is empty (null), which is not fine. 
    1. No its not
    2. If you clear your local storage (or in console, application tab, and you click Clear Site Data)
    3. You refresh the application
    4. By default the App is going to load the default Vuex State
    5. Which has both pub/priv key, and the default state of the config

Now I'm not sure what process you followed to have this issue, can you write it up step by step so I can replicate it?

 1. Also when you click "Save" nothing happens the configuration is not updated in the editor. In my opinion, we should load the application with the default config that we have set for the playground. 
    1. I don't think this statement is correct, or maybe I'm misunderstanding. From `testing.playground.aepps.com` I can save the config.
    4. `we should load the application with the default config` -> Already does that.

1. We are setting it because we believe that thus it will deliver the great development experience without any issues. Why do you think that with the current version of the playgroudn we should load the configs from the local storage?
    1. I'm using Vue Presisted State, and saving only `$store.state.configs` state in local storage.
    2. Also, if you're questioning some of my decisions, please also provide a solution in case you don't think my solution is useful, I would appreciate positive feedback.

1. New users have the error "Cannot read property 'getContractInstance' of null
~ this.instance.compile is not a function" which I guess is because we are reading it from the local storage.
    1. To me this is a well known issue, and has to do with the instance of the SDK, which I'm planing to fix, and to fix this, it has to do with the Abstracting the SDK internally into the Vue App, etc.

I hope this helps Martin.
