### ISSUE TITLE
Research for unit test in vue

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-playground#85]
Research for framework and how test are implemented in vue.

**Comment by sadiqevani** [comment]
Regarding Unit testing and testing in general for `aepp-playground` I would like to use the Vue community tools, and Vue seems to provide a library for testing purposes:


- https://vue-test-utils.vuejs.org

Now, regarding the test runners, Vue suggests two different options:

- https://jestjs.io/docs/en/getting-started#content
- https://github.com/zinserjan/mocha-webpack

This is what they're saying for the options, so we need to make a decision on where should we focus on: 
----
There are a few things to consider when choosing a test runner though: feature set, performance, and support for single-file component (SFC) pre-compilation. After carefully comparing existing libraries, here are two test runners that we recommend:

- Jest is the most fully featured test runner. It requires the least configuration, sets up JSDOM by default, provides built-in assertions, and has a great command line user experience. However, you will need a preprocessor to be able to import SFC components in your tests. We have created the vue-jest preprocessor which can handle most common SFC features, but it currently does not have 100% feature parity with vue-loader.

- mocha-webpack is a wrapper around webpack + Mocha, but with a more streamlined interface and watch mode. The benefits of this setup is that we can get complete SFC support via webpack + vue-loader, but it requires more configuration upfront.

- https://vuejs.org/v2/guide/unit-testing.html
- https://vue-test-utils.vuejs.org/guides/choosing-a-test-runner.html

----

I say we use Jest as test runners, since its a quite popular framework, even though there are missing features, even our test coverage its not going to be that huge, we initially want to use only a few of the features, and as time goes on hopefully Vue Community will implement the extra features.

**Comment by sadiqevani** [comment]
@maptuhec Any ideas/suggestions on this?

**Comment by VladislavIvanov** [comment]
Thumbs up for Jest as test runner from my side.

**Comment by maptuhec** [comment]
Jets sound good enough for me. We can start with it and if we have/see some bottlenecks we can think of a change

**Comment by sadiqevani** [comment]
Then it's decided! 👍
